import React, { useState } from 'react';
import { Hash, Search, TrendingUp, Star, Copy, Download, ArrowLeft, Sparkles, Grid, BarChart3, Heart, Clock, Zap, Filter } from 'lucide-react';

interface HashtagManagerProps {
  onBack?: () => void;
  onNavigate?: (page: string) => void;
}

interface HashtagSet {
  id: string;
  name: string;
  hashtags: string[];
  category: string;
  engagement: number;
  lastUsed: string;
}

interface TrendingHashtag {
  tag: string;
  growth: number;
  posts: string;
  category: string;
}

export function HashtagManager({ onBack }: HashtagManagerProps) {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('all');
  const [selectedSet, setSelectedSet] = useState<HashtagSet | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const categories = [
    'all', 'business', 'lifestyle', 'tech', 'fitness', 'food', 'travel', 'fashion', 'art', 'music'
  ];

  const savedSets: HashtagSet[] = [
    {
      id: '1',
      name: 'Tech Startup',
      hashtags: ['#startup', '#tech', '#innovation', '#entrepreneur', '#ai', '#blockchain'],
      category: 'tech',
      engagement: 8.5,
      lastUsed: '2 hours ago'
    },
    {
      id: '2',
      name: 'Fitness Motivation',
      hashtags: ['#fitness', '#motivation', '#health', '#workout', '#gym', '#fitlife'],
      category: 'fitness',
      engagement: 9.2,
      lastUsed: '1 day ago'
    },
    {
      id: '3',
      name: 'Food Photography',
      hashtags: ['#foodie', '#instafood', '#delicious', '#cooking', '#chef', '#yummy'],
      category: 'food',
      engagement: 7.8,
      lastUsed: '3 days ago'
    }
  ];

  const trendingHashtags: TrendingHashtag[] = [
    { tag: '#aiart', growth: 156, posts: '2.3M', category: 'tech' },
    { tag: '#sustainablefashion', growth: 89, posts: '1.8M', category: 'fashion' },
    { tag: '#remotework', growth: 67, posts: '3.1M', category: 'business' },
    { tag: '#plantbased', growth: 45, posts: '2.7M', category: 'food' },
    { tag: '#mindfulness', growth: 38, posts: '1.9M', category: 'lifestyle' },
  ];

  const handleGenerateHashtags = async () => {
    if (!searchQuery.trim()) return;

    setIsGenerating(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 1500));

      const mockHashtags = [
        `#${searchQuery.toLowerCase().replace(/\s+/g, '')}`,
        `#${searchQuery.toLowerCase()}trends`,
        `#viral${searchQuery.toLowerCase()}`,
        '#trending',
        '#viral',
        '#fyp',
        '#explore',
        '#discover',
        '#instadaily',
        '#socialmedia'
      ];

      const newSet: HashtagSet = {
        id: Date.now().toString(),
        name: `Generated: ${searchQuery}`,
        hashtags: mockHashtags,
        category: selectedCategory === 'all' ? 'business' : selectedCategory,
        engagement: Math.floor(Math.random() * 3 + 7),
        lastUsed: 'Just now'
      };

      setSelectedSet(newSet);
    } catch (error) {
      console.error('Hashtag generation error:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleCopyHashtags = (hashtags: string[]) => {
    navigator.clipboard.writeText(hashtags.join(' '));
  };

  const handleDownloadHashtags = (set: HashtagSet) => {
    const content = `Hashtag Set: ${set.name}
Category: ${set.category}
Engagement Score: ${set.engagement}/10
Last Used: ${set.lastUsed}

Hashtags:
${set.hashtags.join('\n')}

Generated by Viral Hashtag & Image AI Platform`;

    const element = document.createElement('a');
    const file = new Blob([content], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `hashtags-${set.name.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-950 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-8">
          {onBack && (
            <button
              onClick={onBack}
              className="p-2 rounded-lg bg-slate-800 border border-slate-700 text-slate-300 hover:text-white transition-colors"
            >
              <ArrowLeft className="w-5 h-5" />
            </button>
          )}
          <div className="flex items-center gap-3">
            <div className="p-3 rounded-xl bg-gradient-to-r from-purple-500 to-pink-500">
              <Hash className="w-6 h-6 text-white" />
            </div>
            <div>
              <h1 className="text-3xl font-bold text-white">Hashtag Manager</h1>
              <p className="text-slate-400">Your central hub for viral hashtag management</p>
            </div>
          </div>
        </div>

        {/* Stats Dashboard */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-blue-500/20 rounded-lg">
                <Hash className="w-5 h-5 text-blue-400" />
              </div>
              <div>
                <p className="text-slate-400 text-sm">Total Sets</p>
                <p className="text-2xl font-bold text-white">12</p>
              </div>
            </div>
          </div>

          <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-green-500/20 rounded-lg">
                <TrendingUp className="w-5 h-5 text-green-400" />
              </div>
              <div>
                <p className="text-slate-400 text-sm">Avg Engagement</p>
                <p className="text-2xl font-bold text-white">8.2</p>
              </div>
            </div>
          </div>

          <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-purple-500/20 rounded-lg">
                <Star className="w-5 h-5 text-purple-400" />
              </div>
              <div>
                <p className="text-slate-400 text-sm">Favorites</p>
                <p className="text-2xl font-bold text-white">5</p>
              </div>
            </div>
          </div>

          <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-orange-500/20 rounded-lg">
                <Zap className="w-5 h-5 text-orange-400" />
              </div>
              <div>
                <p className="text-slate-400 text-sm">Generated Today</p>
                <p className="text-2xl font-bold text-white">3</p>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
          {/* Generation & Search */}
          <div className="xl:col-span-2 space-y-8">
            {/* Hashtag Generator */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
              <h2 className="text-xl font-semibold text-white mb-4 flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-purple-400" />
                Generate New Hashtags
              </h2>

              <div className="space-y-4">
                <div className="flex gap-4">
                  <input
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder="Enter topic, keyword, or description..."
                    className="flex-1 p-3 bg-slate-900/50 border border-slate-600 rounded-lg text-white placeholder-slate-400 focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                  />
                  <select
                    value={selectedCategory}
                    onChange={(e) => setSelectedCategory(e.target.value)}
                    className="p-3 bg-slate-900/50 border border-slate-600 rounded-lg text-white focus:ring-2 focus:ring-purple-500"
                  >
                    {categories.map(category => (
                      <option key={category} value={category}>
                        {category.charAt(0).toUpperCase() + category.slice(1)}
                      </option>
                    ))}
                  </select>
                </div>

                <button
                  onClick={handleGenerateHashtags}
                  disabled={!searchQuery.trim() || isGenerating}
                  className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-3 px-6 rounded-lg transition-all duration-200"
                >
                  {isGenerating ? (
                    <>
                      <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                      Generating...
                    </>
                  ) : (
                    <>
                      <Hash className="w-5 h-5" />
                      Generate Hashtags
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Generated Result */}
            {selectedSet && (
              <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
                <div className="flex items-center justify-between mb-4">
                  <h3 className="text-lg font-semibold text-white">{selectedSet.name}</h3>
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleCopyHashtags(selectedSet.hashtags)}
                      className="p-2 bg-slate-700 hover:bg-slate-600 text-slate-300 hover:text-white rounded-lg transition-colors"
                      title="Copy hashtags"
                    >
                      <Copy className="w-4 h-4" />
                    </button>
                    <button
                      onClick={() => handleDownloadHashtags(selectedSet)}
                      className="p-2 bg-slate-700 hover:bg-slate-600 text-slate-300 hover:text-white rounded-lg transition-colors"
                      title="Download set"
                    >
                      <Download className="w-4 h-4" />
                    </button>
                  </div>
                </div>

                <div className="flex flex-wrap gap-2 mb-4">
                  {selectedSet.hashtags.map((tag, index) => (
                    <span
                      key={index}
                      className="px-3 py-1 bg-purple-500/20 border border-purple-500/30 text-purple-300 rounded-full text-sm"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="flex items-center justify-between text-sm text-slate-400">
                  <span>Engagement Score: {selectedSet.engagement}/10</span>
                  <span>Category: {selectedSet.category}</span>
                </div>
              </div>
            )}

            {/* Saved Sets */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <Grid className="w-5 h-5 text-blue-400" />
                Saved Hashtag Sets
              </h3>

              <div className="space-y-3">
                {savedSets.map((set) => (
                  <div key={set.id} className="bg-slate-900/50 border border-slate-600 rounded-lg p-4">
                    <div className="flex items-center justify-between mb-2">
                      <h4 className="font-medium text-white">{set.name}</h4>
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleCopyHashtags(set.hashtags)}
                          className="p-1 text-slate-400 hover:text-white transition-colors"
                        >
                          <Copy className="w-4 h-4" />
                        </button>
                        <button
                          onClick={() => handleDownloadHashtags(set)}
                          className="p-1 text-slate-400 hover:text-white transition-colors"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-1 mb-2">
                      {set.hashtags.slice(0, 4).map((tag, index) => (
                        <span key={index} className="text-xs text-purple-300 bg-purple-500/10 px-2 py-1 rounded">
                          {tag}
                        </span>
                      ))}
                      {set.hashtags.length > 4 && (
                        <span className="text-xs text-slate-400">+{set.hashtags.length - 4} more</span>
                      )}
                    </div>

                    <div className="flex items-center justify-between text-xs text-slate-400">
                      <span className="flex items-center gap-1">
                        <BarChart3 className="w-3 h-3" />
                        {set.engagement}/10
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {set.lastUsed}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Trending & Analytics Sidebar */}
          <div className="space-y-8">
            {/* Trending Hashtags */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-green-400" />
                Trending Now
              </h3>

              <div className="space-y-3">
                {trendingHashtags.map((hashtag, index) => (
                  <div key={index} className="flex items-center justify-between p-3 bg-slate-900/50 border border-slate-600 rounded-lg">
                    <div>
                      <p className="font-medium text-white">{hashtag.tag}</p>
                      <p className="text-xs text-slate-400">{hashtag.posts} posts</p>
                    </div>
                    <div className="text-right">
                      <p className="text-green-400 text-sm font-medium">+{hashtag.growth}%</p>
                      <p className="text-xs text-slate-400 capitalize">{hashtag.category}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Quick Actions */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Quick Actions</h3>

              <div className="space-y-3">
                <button className="w-full p-3 bg-gradient-to-r from-purple-600/20 to-pink-600/20 border border-purple-500/30 rounded-lg text-purple-300 hover:bg-gradient-to-r hover:from-purple-600/30 hover:to-pink-600/30 transition-all">
                  Analyze Hashtag Performance
                </button>
                <button className="w-full p-3 bg-gradient-to-r from-blue-600/20 to-cyan-600/20 border border-blue-500/30 rounded-lg text-blue-300 hover:bg-gradient-to-r hover:from-blue-600/30 hover:to-cyan-600/30 transition-all">
                  Competitor Analysis
                </button>
                <button className="w-full p-3 bg-gradient-to-r from-green-600/20 to-emerald-600/20 border border-green-500/30 rounded-lg text-green-300 hover:bg-gradient-to-r hover:from-green-600/30 hover:to-emerald-600/30 transition-all">
                  Export All Data
                </button>
              </div>
            </div>

            {/* Recent Activity */}
            <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6">
              <h3 className="text-lg font-semibold text-white mb-4">Recent Activity</h3>

              <div className="space-y-3">
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-2 h-2 bg-green-400 rounded-full"></div>
                  <span className="text-slate-300">Generated "Tech Startup" set</span>
                  <span className="text-slate-500 ml-auto">2h</span>
                </div>
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-2 h-2 bg-blue-400 rounded-full"></div>
                  <span className="text-slate-300">Copied "Fitness Motivation"</span>
                  <span className="text-slate-500 ml-auto">4h</span>
                </div>
                <div className="flex items-center gap-3 text-sm">
                  <div className="w-2 h-2 bg-purple-400 rounded-full"></div>
                  <span className="text-slate-300">Favorited trending hashtag</span>
                  <span className="text-slate-500 ml-auto">1d</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Coming Soon Notice */}
        <div className="mt-8 bg-gradient-to-r from-purple-500/10 to-pink-500/10 border border-purple-500/20 rounded-xl p-6">
          <h3 className="text-lg font-semibold text-white mb-2">🚀 Coming Soon</h3>
          <p className="text-slate-300">
            Advanced hashtag analytics, AI-powered engagement predictions, competitor analysis,
            automated posting schedules, and integration with major social media platforms.
          </p>
        </div>
      </div>
    </div>
  );
}

export default HashtagManager;