import JSZip from 'jszip';
import { saveAs } from 'file-saver';

// Extract images from HTML and convert data URLs to files
export const extractImagesFromHtml = (htmlContent: string): { filename: string; data: string }[] => {
  const images: { filename: string; data: string }[] = [];
  
  // Regular expression to match data URLs in img tags
  const dataUrlRegex = /<img[^>]+src="(data:image\/([^;]+);base64,([^"]+))"[^>]*>/g;
  let match;
  let imageIndex = 0;
  
  while ((match = dataUrlRegex.exec(htmlContent)) !== null) {
    const fullDataUrl = match[1];
    const imageType = match[2]; // png, jpeg, etc.
    const base64Data = match[3];
    
    // Generate a filename
    const filename = `image${imageIndex}.${imageType}`;
    
    images.push({
      filename,
      data: base64Data
    });
    
    imageIndex++;
  }
  
  return images;
};

// Replace data URLs with local file references in HTML
export const replaceDataUrlsWithLocalPaths = (htmlContent: string): string => {
  let updatedHtml = htmlContent;
  const dataUrlRegex = /<img[^>]+src="(data:image\/([^;]+);base64,([^"]+))"[^>]*>/g;
  let match;
  let imageIndex = 0;
  
  while ((match = dataUrlRegex.exec(htmlContent)) !== null) {
    const fullMatch = match[0];
    const imageType = match[2];
    const filename = `image${imageIndex}.${imageType}`;
    
    // Replace the data URL with a local file reference
    const replacement = fullMatch.replace(
      /src="[^"]+"/,
      `src="${filename}"`
    );
    
    updatedHtml = updatedHtml.replace(fullMatch, replacement);
    imageIndex++;
  }
  
  return updatedHtml;
};

// Create and download ZIP file with website content
export const downloadWebsiteAsZip = async (
  htmlContent: string, 
  websiteTitle: string,
  onProgress?: (progress: number) => void
): Promise<void> => {
  const zip = new JSZip();
  
  // Extract and process images
  const images = extractImagesFromHtml(htmlContent);
  const updatedHtml = replaceDataUrlsWithLocalPaths(htmlContent);
  
  // Add HTML file
  zip.file('index.html', updatedHtml);
  
  // Add images to ZIP
  images.forEach((image, index) => {
    const imageBlob = base64ToBlob(image.data, `image/${image.filename.split('.')[1]}`);
    zip.file(image.filename, imageBlob);
    
    // Update progress if callback provided
    if (onProgress) {
      const progress = Math.round(((index + 1) / (images.length + 1)) * 100);
      onProgress(progress);
    }
  });
  
  // Generate ZIP file
  const zipBlob = await zip.generateAsync({ type: 'blob' }, (metadata) => {
    if (onProgress) {
      onProgress(metadata.percent);
    }
  });
  
  // Download the ZIP file
  const filename = `${websiteTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_website.zip`;
  saveAs(zipBlob, filename);
};

// Convert base64 string to Blob
const base64ToBlob = (base64: string, mimeType: string): Blob => {
  const byteCharacters = atob(base64);
  const byteArrays = [];
  
  for (let offset = 0; offset < byteCharacters.length; offset += 512) {
    const slice = byteCharacters.slice(offset, offset + 512);
    
    const byteNumbers = new Array(slice.length);
    for (let i = 0; i < slice.length; i++) {
      byteNumbers[i] = slice.charCodeAt(i);
    }
    
    const byteArray = new Uint8Array(byteNumbers);
    byteArrays.push(byteArray);
  }
  
  return new Blob(byteArrays, { type: mimeType });
};

// Create a simple README file for the website
export const createReadmeContent = (websiteTitle: string): string => {
  return `# ${websiteTitle}

## Website Generated by AV Artist Assistant

This website was generated using the AV Artist Assistant AI tool.

### How to Use
1. Extract all files from this ZIP folder
2. Open \`index.html\` in your web browser
3. The website should display correctly with all images and styling

### Features
- Self-contained HTML file with embedded CSS (Tailwind CDN)
- All images included as separate files
- Responsive design
- No external dependencies required

### Notes
- If images don't display, ensure all image files are in the same folder as index.html
- For best results, serve from a local web server or upload to a hosting service

---
Generated on: ${new Date().toLocaleDateString()}
`;
};